apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce # Solo un nodo puede escribir a la vez
  resources:
    requests:
      storage: 1Gi # Pedimos 1 Gigabyte
