apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres # Esto generará "sistema-actual-postgres"
spec:
  selector:
    app: postgres # Esto le dice al Service que busque los Pods con esta etiqueta
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
