apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  # Helm tiene una función para pasar a Base64 automáticamente
  POSTGRES_PASSWORD: {{ .Values.postgresConfig.password | b64enc | quote }}
