server {
    listen 80;

    # Proxy hacia el backend (service discovery: nombre del servicio "backend")
    location / {
        proxy_pass http://backend:8000;

        # headers típicos para proxy
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
