# 1. Definimos el molinete (Zona de memoria)
# Guardamos las IPs en 10MB de RAM y limitamos a 5 peticiones por segundo (5r/s)
limit_req_zone $binary_remote_addr zone=ratelimit_backend:10m rate=5r/s;

server {
    listen 80;

    # Proxy hacia el backend
    location / {
        # 2. Aplicamos la regla
        # burst=10 permite ráfagas de 10 pedidos antes de empezar a rebotar gente
        # nodelay hace que el rebote (error 503/429) sea instantáneo
        limit_req zone=ratelimit_backend burst=10 nodelay;

        proxy_pass http://backend:8000;

        # headers típicos para proxy
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
