name: CI/CD a AWS ECR (Bunker Privado)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    # 1. Nos ponemos el uniforme de AWS (Autenticación)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 2. Le pedimos permiso al portero de ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. Preparamos las etiquetas (v1.0.2, latest, etc)
    - name: Extraer metadatos de Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        # Usamos tu URL real de AWS que sacamos del ARN
        images: 120415017560.dkr.ecr.us-east-2.amazonaws.com/sistema-final-backend
        tags: |
          type=semver,pattern={{version}}
          type=raw,value=latest

    # 4. Construimos una imagen local para que Trivy la revise
    - name: Construir Imagen (para escaneo)
      run: docker build -t backend:test ./backend

    # 5. Escaneo de Seguridad (¡No entra nada roto al búnker!)
    - name: Escaneo con Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'backend:test'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    # 6. El Empuje Final a AWS
    - name: Subir Imagen a AWS ECR
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
   # 7. Conectar al Cluster de Kubernetes (EKS en AWS)
    - name: Configurar conexión a Kubernetes
      run: aws eks update-kubeconfig --name cluster-bot-trading --region ${{ secrets.AWS_REGION }}

    # 8. Desplegar la artillería pesada (Manifiestos YAML)
    - name: Desplegar en Kubernetes
      run: |
        kubectl apply -f ./k8s/backend-deployment.yaml
        kubectl apply -f ./k8s/hpa.yaml
        # Si tenés el ingress o service ahí, también los aplicamos con:
        # kubectl apply -f ./k8s/
